//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bancolombia.Riesgo.MAFWeb.CalificacionCartera.Master {
    
    
    public partial class General {
        
       
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        
       
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        
        protected global::System.Web.UI.WebControls.Label lblUsuario;
        
      
        protected global::System.Web.UI.WebControls.ListView lsvMenu;
        
       
        protected global::System.Web.UI.WebControls.Label lblPeriodos;
     
        protected global::System.Web.UI.WebControls.ListView lsvPeriodos;
     
        protected global::System.Web.UI.WebControls.LinkButton lbSalir;
        
   
        protected global::System.Web.UI.WebControls.Label lblTitulo;
        
      
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}
